version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /service
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /service/data_generator_service
    schedule:
      interval: daily
